graffish_labs_nats_transport:
    enabled: true
    nats_transport_factory:
        class: GraffishLabs\SymfonyNatsTransport\Transport\NatsTransportFactory
        tags: [messenger.transport_factory]

    nats_transport:
        class: GraffishLabs\SymfonyNatsTransport\Transport\NatsTransport
        tags: [messenger.transport]