name: Cleanup Flex testing endpoint

on:
    pull_request_target:
        types: [ closed ]

defaults:
    run:
        shell: bash

jobs:
    call-flex-cleanup:
        uses: graffish-labs/recipes/.github/workflows/callable-flex-cleanup.yml@main
